name: 'Get Strongest Version Label In PR'
description: 'Returns string depending on the strongest exist label in PR'
inputs:
  GitHubToken:
    description: 'GitHub Token for getting the pull request'
    required: true

  labels:
    description: 'Wanted labels ORDERED from the most important to the less (Available formats explained in the README)'
    required: true

outputs:
  strongestLabelName:
    description: 'The strongest label name exist (`input.minor` is `bump:minor` and `input.patch` is `bump:patch` so the `strongestLabel` is `bump:minor`)'

  strongestLabelValue:
    description: 'The value of strongestLabel (`input.major` is `bump:major` so the `strongestLabelText` is `major`)'

  error:
    description: 'No error - 0 | If the push wasnt from merging pull request - 1 | If no matching label - 2'

runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'check'
  color: 'blue'
